### ISSUE TITLE
[Visual Studio Enterprise 16 ml] Failed to install Chutzpah Test Adapter for the Test Explorer

### ISSUE THREAD

**Issue by Jiayili1** [mmanela/chutzpah#722]
Affected Branch: lab/ml
Affected Build: 28009.4003.ml
Affected Product Language: 

Steps to reproduce:

 1. Open Visual Studio, go to Tools -> Extensions and Updates -> Online, search "chutzpah"

2. Download "Chutzpah Test Adapter for the Test Explorer"

3. Close vs to finish installing

Expected Result: Chutzpah could be installed successfully

Actual Result:

Installed failed

From the log, there is the error:

8/14/2018 1:03:17 AM - Extension cannot be installed to the following products due to missing prerequisites:
8/14/2018 1:03:17 AM -  Microsoft Visual Studio Enterprise 16
8/14/2018 1:03:17 AM -   -------------------------------------------------------
8/14/2018 1:03:17 AM -   Identifier   : Microsoft.VisualStudio.Component.CoreEditor
8/14/2018 1:03:17 AM -   Name         : Visual Studio core editor
8/14/2018 1:03:17 AM -   Version      : [15.0,16.0)
8/14/2018 1:03:17 AM -   Error        : The prerequisite version specified does not match the version installed
8/14/2018 1:03:17 AM - 
8/14/2018 1:03:17 AM - System.InvalidOperationException: No modifications could be applied.
   at VSIXInstaller.MultipleChangePage..ctor(ExtensionData data)
   at VSIXInstaller.LoadingPage.<>c__DisplayClass15_1.<OnLoaded>b__2()

**Comment by mmanela** [comment]
I just updated and this should work now, let me know

**Comment by Jiayili1** [comment]
Checked this issue still repro with [28119.401.ml]:

9/25/2018 1:15:09 AM - 	Supported Products : 
9/25/2018 1:15:09 AM - 		Microsoft.VisualStudio.Pro
9/25/2018 1:15:09 AM - 			Version : [14.0,)
9/25/2018 1:15:09 AM - 		Microsoft.VisualStudio.IntegratedShell
9/25/2018 1:15:09 AM - 			Version : [14.0,)
9/25/2018 1:15:09 AM - 		Microsoft.VisualStudio.Premium
9/25/2018 1:15:09 AM - 			Version : [14.0,)
9/25/2018 1:15:09 AM - 		Microsoft.VisualStudio.Ultimate
9/25/2018 1:15:09 AM - 			Version : [14.0,)
9/25/2018 1:15:09 AM - 		Microsoft.VisualStudio.Community
9/25/2018 1:15:09 AM - 			Version : [14.0,)
9/25/2018 1:15:09 AM - 
9/25/2018 1:15:09 AM - 	References         : 
9/25/2018 1:15:09 AM - 		-------------------------------------------------------
9/25/2018 1:15:09 AM - 		Identifier   : Microsoft.VisualStudio.MPF.14.0
9/25/2018 1:15:09 AM - 		Name         : Visual Studio MPF 14.0
9/25/2018 1:15:09 AM - 		Version      : [14.0]
9/25/2018 1:15:09 AM - 		MoreInfoURL  : 
9/25/2018 1:15:09 AM - 		Nested       : No
9/25/2018 1:15:09 AM - 
9/25/2018 1:15:09 AM - 	Prerequisites      : 
9/25/2018 1:15:09 AM - 		-------------------------------------------------------
9/25/2018 1:15:09 AM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
9/25/2018 1:15:09 AM - 		Name         : Visual Studio core editor
9/25/2018 1:15:09 AM - 		Version      : [15.0,16.0)

**Comment by Jiayili1** [comment]
@mmanela Thanks, it works now.
